### ISSUE TITLE
Investigate clipboard

### ISSUE THREAD

**Issue by RunDevelopment** [chaiNNer-org/chaiNNer-rs#3]
We long sought to have one dependency for copying text and images to clipboard. The python ecosystem doesn't have good-enough answers, but arboard seems promising.

https://crates.io/crates/arboard
https://github.com/1Password/arboard

**Comment by joeyballentine** [comment]
Is this something we should include here or is it something you think we should publish as its own python package?

**Comment by RunDevelopment** [comment]
Here first. We can move it into its own package later. `chainner_ext` is purely internal for chainner right now, so we can experiment.
